# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Charybdis'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["bastardkb/charybdis/3x5/v2/splinky_3"]'
